### ISSUE TITLE
Should most database operations be made to take `&self` and not `&mut self`?

### ISSUE THREAD

**Issue by emchristiansen** [skytable/client-rust#17]
I'm a relative Rust noob so this question may be off-base, but I noticed that most of the database operations take _mutable_ references to the database, e.g. `get` uses this codepath: https://github.com/skytable/client-rust/blob/d6ca102e4c74dc7797d8639bf85ae42436f42584/src/actions.rs#L119

As I said I'm a noob, but this makes it very hard (impossible?) to send several requests concurrently over the same connection, because Rust only lets at most one mutable borrow exist for a given object at any time.

For comparison, RocksDB (which also allows concurrent access) treats most database operations as non-mutating, making it substantially easier to use with futures, e.g.: https://github.com/rust-rocksdb/rust-rocksdb/blob/b5b9e56d084aec2460bb50851757519b0387e198/src/db.rs#L939

If I'm wrong and it is easy to spin off dozens of concurrent futures which interact with the database, could you add such an example to the examples folder?
If not, consider marking these methods as non-mutable?

**Comment by ohsayan** [comment]
The underlying connection type would need a mutable reference to write any data (see impl and definition for the `Write` and `AsyncWrite` traits), which is why the actions accept mutable references. In Rust, mutable references are mutually exclusive to immutable references (so you can have a single `&mut T` or multiple `&T`s).

Regarding sending queries concurrently (and assuming you do not mean parallelism), in this library-specific scenario, you can utilize pipelining to send multiple queries _at the same time_. Multiplexed queries are still experimental (and not available for public use right now).

**Comment by ohsayan** [comment]
If you wanted to utilize multiple threads for sending queries, considering looking at the available connection pool implementations: https://docs.rs/skytable/latest/skytable/pool/index.html

**Comment by emchristiansen** [comment]
You're referring to, e.g., `AsyncWrite` here?
https://github.com/skytable/client-rust/blob/c57e46e6ddce57c221e41cd038e7eb8296d2d732/src/lib.rs#L426

I see that you're mutating `stream` in implementing [`tokio::io::AsyncWrite`](https://docs.rs/tokio/latest/tokio/io/trait.AsyncWrite.html), and that forces the existence of an `&mut`.
But maybe you could use a mutex here to serialize the writes, so the API one level up wouldn't need to take an `&mut`?
If the writes are fast then serializing through a mutex might be very cheap, and it would make it much easier for the user to write concurrent code.

If this is unnecessary, could you prove it?
E.g. add an example to the examples folder that concurrently fetches 10000 `i32`s from a database of type `(String, i32)`, increments each `i32`, then saves the results back to the database?
As a Rust noob I have no idea how to do that without having 10000 simultaneous connections, and even that approach isn't elegant.

**Comment by ohsayan** [comment]
> maybe you could use a mutex here to serialize the writes

Using a mutex in a single threaded scenario would only waste time due to slower atomic instructions. In a multi-threaded scenario, you will **not** get any concurrency, since a mutex provides mutual exclusion, i.e only one thread will be able to use the connection at a time. If you wanted to share it, on top of that, you'll need to wrap it in an `Arc` to make it `Send` (since a mutex is `!Send`)

**Comment by ohsayan** [comment]
> If the writes are fast then serializing through a mutex might be very cheap

Writing to a server over a network cannot be classified as a "fast" operation, especially when you're talking about synchronization

**Comment by ohsayan** [comment]
> As a Rust noob I have no idea how to do that without having 10000 simultaneous connections, and even that approach isn't elegant.

You could:
- Pipeline it: if you wanted to use a single thread (so you send 10000 queries over the same connection in one go)
- Use a connection pool: Say spawn it with 10 threads and then send 10K queries over the 10 different connections (edit: reworded to avoid confusion)

**Comment by ohsayan** [comment]
I'll recommend you to read `std`'s documentation on
- the `sync` module covering when to use `Mutex`es and other synchronization primitives: https://doc.rust-lang.org/stable/std/sync/index.html.
- the [`Send`](https://doc.rust-lang.org/stable/std/marker/trait.Send.html) and [`Sync`](https://doc.rust-lang.org/stable/std/marker/trait.Sync.html) marker traits

Let me know if you have any other questions :)
